sudo: false
language: node_js
node_js:
  - '7.9'
before_script:
- npm install -g istanbul codeclimate-test-reporter
after_script:
- CODECLIMATE_REPO_TOKEN=1cd6bb8d13deda8a9d285419168be22248bd1bb8eca26385fdcea322c3972ab7 codeclimate-test-reporter < coverage/lcov.info