sudo: false
language: node_js
node_js:
  - '7.9'
before_script:
- npm install -g istanbul codeclimate-test-reporter
after_script:
- CODECLIMATE_REPO_TOKEN=f2af390836a76e9b57b192d7cae4557d7bbebe4f8c644f23dbaf8bbf3a963e23 codeclimate-test-reporter < coverage/lcov.info